### PR TITLE
AP-12: Removed hard dependency on Atom feed.

### PR DESCRIPTION
**Pull request by ibacher**
This refactors things so that the module does not require AtomFeed. This is done by:

1. Marking the module as "aware of" AtomFeed rather than requiring AtomFeed
2. Moving the Advice classes which need AtomFeed class into their own separate Jar
3. Ensuring that this Jar is only loaded when the AtomFeed module is present

This should ensure that the module continues to work in Bahmni but can be used in non-Bahmni versions of OpenMRS that would prefer not to use AtomFeed.

### CODE REVIEW

**Comment by gsluthra** [comment]
@binduak - Does this affect your team too? Can your team also provide review comments to this?

**Review by angshu — APPROVED** [review]

**Comment by binduak** [comment]
Hi @angshu @gsluthra The data from openmrs to Bahmni-mart sync works based on the atomfeed events. So we need atomfeed events for appointments module. But from card we could see that the events may/may not generate with the PR changes.

**Comment by gsluthra** [comment]
@binduak From what I understand, it should work for Bahmni with atomfeed+advice jars being present. You can test and validate. For others who need appointment module outside of Bahmni, they can choose to not have these jars (and this module should work for them). Yes-in that case Bahmni mart won't be available to them, which should be fine.

**Comment by binduak** [comment]
@ibacher @gsluthra @angshu atomfeed events are generating with the PR changes for appointments. Approved the PR !

**Review by binduak — APPROVED** [review]

**Pull request merged**
